<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-12-15 at 11:20:29.
 */
class Die6Test extends \PHPUnit\Framework\TestCase
{
    /**
     * @var Die6
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Die6;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers Die6::roll
     * @todo   Implement testRoll().
     */
    public function testRollReturnsXNumberOfRandomInts()
    {
        $OneD6 = new Die6(1);
        $TwoD6 = new Die6(2);
        $TenD6 = new Die6(10);
        $this->assertCount(1, $OneD6->roll());
        $this->assertCount(2, $TwoD6->roll());
        $this->assertCount(10, $TenD6->roll());
    }

    /**
     * @covers Die6::lastRolls
     * @todo   Implement testLastRolls().
     */
    public function testLastRolls()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
